server:
  port: 8081
spring:
  application:
    name: dianping
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/DianPing?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  redis:
    host: 192.168.10.102
    port: 6379
    password: 123321
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  rabbitmq:
    host: 192.168.10.102
    port: 5672
    virtual-host: / # 虚拟主机
    username: root  # 用户名
    password: 123321
    listener: # 收消息
      simple:
        prefetch: 1 # 每次只能获取一消息，处理完成才能获取下一个消息
        concurrency: 1 # 消费端的监听个数(即@RabbitListener开启几个线程去处理数据。)
        max-concurrency: 10 # 消费端的监听最大个数
        acknowledge-mode: manual # auto
        default-requeue-rejected: false # 默认是true，表示被拒绝的消息重新入队；false表示需要手动入队
        retry:
          enabled: true # 开启消费者失败重试
          initial-interval: 1000ms # 初始化失败等待时长为1秒
          multiplier: 2 # 下次失败的等待次数倍数，下次等待时长=multiplier*last-interval
          stateless: true # true无状态；false有状态。如果业务中包含事务，这里改为false
          max-attempts: 3 # 最大重试次数

    template: # 发消息
      retry:
        enabled: true # 开启超时重试机制
        initial-interval: 200ms # 失败后的初始等待时间
        multiplier: 2 # 失败后下次的等待时长背书，下次等待时=initial-interval * multiplier
        max-attempts: 3 # 最大重试次数


    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型。
    publisher-returns: false # 开启publisher return机制（这个一般是key写错了导致的，一般不开启）

  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
mybatis-plus:
  type-aliases-package: com.dianping.entity # 别名扫描包
logging:
  level:
    com.dianping: debug