---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 16404.
--- DateTime: 2024/12/22 23:38
---
-- 1.参数列表
-- 1.1. 优惠券id
local voucherId = ARGV[1]
-- 1.2. 用户id
local userId = ARGV[2]

-- 2. 数据key
-- 2.1. 库存key
local stockKey = 'seckill:stock:'..voucherId
-- 2.2. 订单key
local orderKey = 'seckill:order:'..voucherId

-- 3. 脚本业务
-- 3.1. 判断用户是否下单
if(redis.call('sismember', orderKey, userId) ~= 1) then
    -- 3.1. redis并未实现用户下单和库存扣减
    return 0
end
-- 3.2. 删除用户的下单记录
redis.call('srem', orderKey, userId)
-- 3.3. 恢复库存
redis.call('incrby', stockKey, 1)

return 0